services:

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION:-8.19.11}
    container_name: elk-logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "5044:5044"
      - "5001:5000"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logs:/var/log/demo:ro
      - ./log_analysed:/var/log/analysed:ro
      - ./python_apps/logs:/var/log/apps:ro
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - observability


  server:
    build:
      context: ./python_apps_with_db/server
      dockerfile: Dockerfile
    container_name: demo-server
    environment:
      - SERVICE_NAME=server
      - LOG_FILE=/var/log/apps/server.log
      - OTEL_RESOURCE_ATTRIBUTES=service.name=api-server
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    volumes:
      - ./python_apps/logs:/var/log/apps
    ports:
      - "5002:5000"
    depends_on:
      - postgres
    networks:
      - observability


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - DB_HOST=db 
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U observability_user -d observability_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observability


  client:
    build:
      context: ./python_apps_with_db/client
      dockerfile: Dockerfile
    container_name: demo-client
    environment:
      - SERVER_URL=http://server:5000
      - SERVICE_NAME=client
      - LOG_FILE=/var/log/apps/client.log
      - OTEL_RESOURCE_ATTRIBUTES=service.name=api-client
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    volumes:
      - ./python_apps/logs:/var/log/apps
    depends_on:
      - server
      - postgres
    networks:
      - observability

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-8.19.11}
    container_name: elk-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION:-8.19.11}
    container_name: elk-kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - observability

networks:
  observability:

volumes:
  esdata:
